version: '3'

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - ./backend-infra/postgres:/data/postgres
      - ./backend-infra/sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  api:
    container_name: spring-boot-docker
    image: spring-boot-docker
    build: .
    depends_on:
      - db
    networks:
      - postgres
    ports:
      - "9001:9001"
    volumes:
      - .
networks:
  postgres:
    driver: bridge

volumes:
  postgres: